### ISSUE TITLE
Whenever a user searches for a city, the Find Location form should automatically close to enhance user experience.

### ISSUE THREAD

**Issue by Ath47** [patthoege/weather-app#1]
When I search for a particular city and click on the list, the form should automatically close instead of me having to close it.
Will you assign it to me ?

**Comment by patthoege** [comment]
I was aware of this issue as well, and I completely agree—it’s been annoying me too! I'm really glad you’re interested in tackling this. I’d be more than happy to hand it over to you.

Thanks for stepping in! Let me know if you need any additional details or support as you work on it

**Comment by Ath47** [comment]
Alright, I will start working on it, and let you know.
